baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

# Theme Settings
theme = "tale"
[params]
  Author = "Wilfrid NASSARA" # Add the name of the author (this theme only supports one author)
[author]
  name = "Digit Lab" # Used by the foot copyright

googleAnalytics = "" # The UA-XXX number from Google Analytics

